[platformio]
default_envs = esp32-s3-n16r8-cam

[env:esp32-s3-n16r8-cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM
  -D FOLLOWBOX_CAM_WIFI_SSID=\"FollowBox\"
  -D FOLLOWBOX_CAM_WIFI_PASS=\"followbox123\"
  -D FOLLOWBOX_CAM_STATIC_IP=\"192.168.4.2\"
  -D FOLLOWBOX_CAM_GATEWAY=\"192.168.4.1\"
  -D FOLLOWBOX_CAM_NETMASK=\"255.255.255.0\"
  -D FOLLOWBOX_CAM_STREAM_PORT=81
